### ISSUE TITLE
Improve folder locations

### ISSUE THREAD

**Issue by peschkaj** [peschkaj/soddi#12]
SODDI currently has some specific preferences about where source data is located. This makes it painful to load. 

Example from my own awful documentation:

> The SODDI user interface expects the XML files to be stored in a very specific folder name: MMYYYY SITEINITIALS, like 092013 SO. SODDI will import multiple sites, and it creates a different schema for each site. I just want to import Stack Overflow by itself, all in its own database, so I like naming my folder “092013 dbo”. That way, it creates the tables in the dbo schema, which is just a little friendlier for demos.

Instead, SODDI should just load the damn data.

**Comment by Jorriss** [comment]
Yes!

**Comment by Jorriss** [comment]
Any thoughts on how the schema issue? I'm in the "damn the schema" group.

**Comment by peschkaj** [comment]
I'm in that camp as well. I'd say we present a textbox to the user and autofill dbo for SQL Server.

I have some tentative Oracle stuff in place that needs implemented out, check out the feature/oracle-support branch. The schema there will be directly tied to the user because it's Oracle and I don't feel like being more clever.

**Comment by Jorriss** [comment]
Assign me to this one.

**Comment by Jorriss** [comment]
I've got two solutions: 

The short term would create a default for the schema (dbo) and would only allow one folder to be loaded at once. This is a bit of a step backwards but it would get rid of that damned folder naming convention,

The longer term fix would allow the user to change the schema and the database (unlike now where only one database can be loaded at a time). This would be a bit rougher because of the UI and connection changes.
